# Generated by Django 2.2.24 on 2021-10-11 14:42

from django.db import migrations, models
import django_uploads_app.ftp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ftp_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ftp_password',
            field=models.CharField(default=django_uploads_app.ftp.utils.create_random_password, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='ftp_quota',
            field=models.PositiveIntegerField(default=1024),
        ),
    ]
